# Generated by Django 3.0.6 on 2020-05-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.CharField(choices=[('Doing', 'Doing'), ('Done', 'Done')], max_length=5),
        ),
    ]
